name: Offline scan with Maven

on: push

jobs:
  build:

    name: Meterian scan 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Meterian Scanner
      uses: MeterianHQ/meterian-github-action@v1.0.13
      with:
        oss: true
        cli_args: --report-console --debug
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CLIENT_VM_PARAMS: -Dmaven.extra.parameters=-s.github/workflows/maven-settings.xml,-ntp,-B
